server:
  port: ${PORT:8888}
  tomcat:
    threads:
      max: 2

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: ${GIT_URI:https://github.com/nila19/spring-cloud-config}
          search-paths: ${GIT_PATH:dev}
          username: ${GIT_UID:nila19}
          password: ${GIT_PWD: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}
          default-label: ${GIT_LABEL:main}
          basedir: ${GIT_BASEDIR:'./cloned2'}
          clone-on-start: true
          force-pull: true
          delete-untracked-branches: true
  security:
    user:
      name: ${CONFIG_UID:root}
      password: ${CONFIG_PWD:s3cr3t}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    defaults:
      enabled: true
